### ISSUE TITLE
Sacar al Frontend

### ISSUE THREAD

**Issue by Leiner117** [Leiner117/Mini-Python#5]
El encargado de front no trabaja
Nos ponen mas trabajo por culpa de él y no hace nada
Ni siquiera trabaja en el IDE
No sabe que es un compilador en semana 13
@Stevennnncz

**Comment by AntJimenezZ** [comment]
Mentira, yo estuve en todas las reuniones y el implicado siempre estuvo presente

**Comment by FabsCR** [comment]
"Wow, parece que estamos viendo una auténtica obra de teatro aquí. En un rincón, tenemos a @Leiner117 exigiendo justicia porque @Stevennnncz en semana 13 no sabe lo que es un compilador (spoiler: no era una pizza 🤯), y en el otro, @AntJimenezZ defendiendo el honor como si fuera el abogado estrella en un juicio de película 🎬. Solo falta que alguien grite '¡Objection!' en el próximo sprint.

Yo mientras tanto, preparándome las palomitas 🍿 para ver cómo termina este duelo épico de developers 😆. ¿Alguien más sintió la tensión o soy solo yo?"
